Input_Filename:
  Charges : Data/Charges_use.csv
  Damages : Data/Damages_use.csv
  Endorse : Data/Endorse_use.csv
  Primary_Person : Data/Primary_Person_use.csv
  Restrict : Data/Restrict_use.csv
  Units : Data/Units_use.csv

Output_Path:
  1: ./Output/Analysis_1
  2: ./Output/Analysis_2
  3: ./Output/Analysis_3
  4: ./Output/Analysis_4
  5: ./Output/Analysis_5
  6: ./Output/Analysis_6
  7: ./Output/Analysis_7
  8: ./Output/Analysis_8
  9: ./Output/Analysis_9
  10: ./Output/Analysis_10

